version: "3.7"
services:
  emp_service:
    build: .
    restart: always
    ports: 
      - 8082:8082
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: priyanshi
      MYSQL_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root