version: "3.7"
services:

  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: priyanshi
      MYSQL_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root
      
  eureka-server :
    image: netflix-eureka:latest
    restart: always
    ports: 
      - 8761:8761
      
  emp_service:
    image: employee:latest
    restart: always
    ports: 
      - 8082:8082
    depends_on:
      - mysql_db
      - eureka-server
    command: 
      - sh -c './wait-for mysql_db:3306 -- npm start'
      - sh -c './wait-for eureka-server:8761 -- npm start'
    
  spring-gateway :
    image: apigateway:latest
    restart: always
    ports: 
      - 7575:7575
    depends_on:
      - eureka-server
      - emp_service
    command: 
      - sh -c './wait-for eureka-server:8761 -- npm start'
      - sh -c './wait-for emp_service:8082 -- npm start'
    
      
  
      
  
  